---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci-ubuntu
    tag: '0.11.6'

platform: linux

inputs:
- name: garden-shed-git
- name: garden-runc-release-git

run:
  path: garden-shed-git/ci/scripts/test.sh
  user: root
